### ISSUE TITLE
Bug: Cannot find modules es3ify + ./L.Routing.Itinerary

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-1#31]
Hi guys,
I wanted to update to your latest map because the npm package is on week old already. When running `npm install` right from your develop branch I get the following errors.

```
> leaflet-control-geocoder@1.5.2 postinstall /data/code/pokemon/PokeMap-1/node_modules/leaflet-control-geocoder
> sh ./scripts/build.sh

Error: Cannot find module 'es3ify' from '/data/code/pokemon/PokeMap-1/node_modules/leaflet-control-geocoder'
    at /data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:46:17
    at process (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:173:43)
    at ondir (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:188:17)
    at load (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:69:43)
    at onex (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:92:31)
    at /data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)

> pokemap-1@0.1.0 postinstall /data/code/pokemon/PokeMap-1
> browserify module/main.js -o pokemap.bundle.js -t es6ify -g browserify-css --standalone PokeMap

Error: Cannot find module './L.Routing.Itinerary' from '/data/code/pokemon/PokeMap-1/node_modules/leaflet-routing-machine/dist'
    at /data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:55:21
    at load (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:69:43)
    at onex (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:92:31)
    at /data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by ukrainian256** [comment]
@johartl can you please try one more time? Think it should be fixed now

**Comment by johartl** [comment]
Now I get these errors

```
> leaflet-control-geocoder@1.5.2 postinstall /data/code/pokemon/PokeMap-1/node_modules/leaflet-control-geocoder
> sh ./scripts/build.sh

Error: Cannot find module 'browserify-shim' from '/data/code/pokemon/PokeMap-1/node_modules/leaflet-control-geocoder'
    at /data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:46:17
    at process (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:173:43)
    at ondir (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:188:17)
    at load (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:69:43)
    at onex (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:92:31)
    at /data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)

> pokemap-1@0.1.0 postinstall /data/code/pokemon/PokeMap-1
> browserify module/main.js -o pokemap.bundle.js -t es6ify -g browserify-css --standalone PokeMap

Error: Cannot find module './L.Routing.Itinerary' from '/data/code/pokemon/PokeMap-1/node_modules/leaflet-routing-machine/dist'
    at /data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:55:21
    at load (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:69:43)
    at onex (/data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:92:31)
    at /data/code/pokemon/PokeMap-1/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:117:15)
```

**Comment by poulzinho** [comment]
Dependencies versions are fixed now. Please try it again

**Comment by johartl** [comment]
Yes it's working again. Thanks!
